server:
  host: localhost
  port: 8080

spring:
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
      format_sql : true

  datasource:
    url: jdbc:mysql://localhost:3306/comment?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy


#logging:
#  level:
#    org:
#      springframework: debug
#      web: debug


